# ─────────────────────────────────────────────────────────────────────────────
# Base image: official Microsoft Playwright image.
#   - Ubuntu 24.04 Noble
#   - Node.js 20 LTS
#   - Chromium, Firefox, WebKit pre-installed at /ms-playwright
#   - All OS-level Chromium dependencies already present
#
# Why this image instead of node:20-alpine?
#   Alpine lacks the glibc + system libs Chromium needs.
#   The Playwright image bundles every dependency, eliminating the
#   "browser not found" / "libglib-2.0.so not found" class of failures.
# ─────────────────────────────────────────────────────────────────────────────

# ─── Stage 1: Install dependencies ───────────────────────────────────────────
FROM mcr.microsoft.com/playwright:v1.55.0-noble AS deps
WORKDIR /app

# Copy package manifests first — Docker caches this layer until they change.
# npm ci: clean install from lock file; produces a reproducible node_modules.
COPY package.json package-lock.json* ./
RUN npm ci

# ─── Stage 2: Build Next.js (standalone output) ───────────────────────────────
FROM mcr.microsoft.com/playwright:v1.55.0-noble AS builder
WORKDIR /app

# Disable telemetry collection during build.
ENV NEXT_TELEMETRY_DISABLED=1

# Tell Playwright where the pre-installed browsers live in this image.
# Without this the build step would try (and fail) to auto-download Chromium.
ENV PLAYWRIGHT_BROWSERS_PATH=/ms-playwright

# Bring in the installed node_modules from the deps stage.
COPY --from=deps /app/node_modules ./node_modules

# Copy the entire source tree.
COPY . .

# Compile TypeScript + bundle — produces .next/standalone/ when output:'standalone'
# is set in next.config.ts (see that file for the flag).
RUN npm run build

# ─── Stage 3: Production runner ───────────────────────────────────────────────
FROM mcr.microsoft.com/playwright:v1.55.0-noble AS runner
WORKDIR /app

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1

# Critical: tells Playwright where Chromium lives inside this image.
# The snapshot API route reads this at runtime via process.env.
ENV PLAYWRIGHT_BROWSERS_PATH=/ms-playwright

# Tells the Node server which port/host to bind.
ENV PORT=3000
ENV HOSTNAME=0.0.0.0

# Non-root user — principle of least privilege.
# Chromium still runs correctly with --no-sandbox when non-root in a container.
RUN groupadd --system --gid 1001 nodejs \
 && useradd  --system --uid 1001 --gid nodejs nextjs

# ── Copy Next.js standalone build ─────────────────────────────────────────────
# `output: 'standalone'` produces a self-contained server in .next/standalone/.
# This directory already contains its own minimal node_modules subtree.
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./

# Static assets and public directory must be copied separately — they are not
# embedded in the standalone bundle.
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static
COPY --from=builder --chown=nextjs:nodejs /app/public ./public

# ── Copy browser-automation packages ──────────────────────────────────────────
# The standalone bundler only includes packages that Next.js statically traces.
# Dynamic imports (playwright, playwright-core) are NOT traced, so we must
# copy them manually into the standalone node_modules directory.
COPY --from=deps --chown=nextjs:nodejs /app/node_modules/playwright      ./node_modules/playwright
COPY --from=deps --chown=nextjs:nodejs /app/node_modules/playwright-core  ./node_modules/playwright-core

USER nextjs

EXPOSE 3000

# Docker HEALTHCHECK — used by Railway, Docker Swarm, and Compose health gates.
# start-period: give Next.js 60 s to start before the first check.
HEALTHCHECK --interval=30s --timeout=15s --start-period=60s --retries=3 \
  CMD curl -f http://localhost:${PORT}/api/health || exit 1

# server.js is the entry point generated by Next.js standalone output.
CMD ["node", "server.js"]
