// Trello API backend route — credentials live here, never exposed to the client.
// Required env vars (add to .env.local):
//   TRELLO_API_KEY   — from https://trello.com/power-ups/admin → API Key
//   TRELLO_TOKEN     — generated token (OAuth or manual from the Trello API page)
//   TRELLO_LIST_ID   — ID of the Trello list to add cards to
//
// Finding TRELLO_LIST_ID:
//   Open your Trello board → pick a list → add ".json" to the board URL:
//   https://trello.com/b/<boardId>.json  (ctrl+F "idList" for a card in that list)

import { NextRequest, NextResponse } from "next/server";
import type { ApiResponse, TrelloCard, VerificationCardPayload } from "@/types";

const TRELLO_BASE = "https://api.trello.com/1";

export async function POST(req: NextRequest): Promise<NextResponse> {
  const apiKey = process.env.TRELLO_API_KEY;
  const token = process.env.TRELLO_TOKEN;
  const listId = process.env.TRELLO_LIST_ID;

  if (!apiKey || !token || !listId) {
    return NextResponse.json<ApiResponse<never>>(
      {
        success: false,
        error:
          "Trello credentials not configured. Set TRELLO_API_KEY, TRELLO_TOKEN, and TRELLO_LIST_ID in .env.local",
      },
      { status: 503 },
    );
  }

  let payload: VerificationCardPayload;
  try {
    payload = await req.json();
  } catch {
    return NextResponse.json<ApiResponse<never>>(
      { success: false, error: "Invalid request body" },
      { status: 400 },
    );
  }

  const cardName = `[BankVerify] ${payload.bankName} — ${payload.probability}% match`;
  const cardDesc = buildDescription(payload);
  const labelColor =
    payload.probability >= 85
      ? "green"
      : payload.probability >= 60
        ? "yellow"
        : "red";

  try {
    const cardRes = await fetch(
      `${TRELLO_BASE}/cards?key=${apiKey}&token=${token}`,
      {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          idList: listId,
          name: cardName,
          desc: cardDesc,
          pos: "top",
        }),
      },
    );

    if (!cardRes.ok) {
      const errText = await cardRes.text();
      return NextResponse.json<ApiResponse<never>>(
        {
          success: false,
          error: `Trello API error: ${cardRes.status} — ${errText}`,
        },
        { status: 502 },
      );
    }

    const trelloCard = await cardRes.json();

    try {
      await fetch(
        `${TRELLO_BASE}/cards/${trelloCard.id}/labels?key=${apiKey}&token=${token}`,
        {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({
            color: labelColor,
            name: `${payload.probability}% match`,
          }),
        },
      );
    } catch {
      // non-fatal
    }

    const result: TrelloCard = {
      id: trelloCard.id,
      name: trelloCard.name,
      desc: trelloCard.desc,
      url: trelloCard.url,
      labels: trelloCard.labels?.map((l: { name: string }) => l.name) ?? [],
      attachments: [],
    };

    return NextResponse.json<ApiResponse<TrelloCard>>({
      success: true,
      data: result,
    });
  } catch (err) {
    return NextResponse.json<ApiResponse<never>>(
      { success: false, error: String(err) },
      { status: 500 },
    );
  }
}

function buildDescription(payload: VerificationCardPayload): string {
  const m = payload.similarityMetrics;
  return [
    "## Bank Template Verification Report",
    "",
    `**Template:** ${payload.bankName}`,
    `**Probability:** ${payload.probability}%`,
    `**Confidence:** ${payload.result.confidence}`,
    "",
    "### Similarity Scores",
    `| Engine | Score |`,
    `|--------|-------|`,
    `| DOM Structure | ${m.domStructure}% |`,
    `| XPath Validation | ${m.xpathValidation}% |`,
    `| URL Similarity | ${m.urlSimilarity}% |`,
    `| Semantic | ${m.semanticSimilarity}% |`,
    `| Visual | ${m.visualSimilarity}% |`,
    "",
    "### Key Findings",
    ...payload.findings.slice(0, 8).map((f) => `- ${f}`),
    payload.result.missingCritical.length > 0
      ? "\n### Missing Critical Elements\n" +
        payload.result.missingCritical.map((m) => `- ⚠️ ${m}`).join("\n")
      : "",
    "",
    `*Generated by BankVerify — ${new Date().toISOString()}*`,
  ]
    .filter((l) => l !== undefined)
    .join("\n");
}
